POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Sulih",
    "email": "sulih055@gmail.com",
    "password": "123",
    "confpassword":"123",
    "role":"admin"
}

###
POST http://localhost:5000/login

{
    "email": "sulih055@gmail.com",
    "password": "12345"
}